/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2017 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 */
package ti.documentscanner;

import android.app.Activity;
import android.content.res.Resources;
import android.graphics.Bitmap;
import android.graphics.Matrix;
import android.media.ExifInterface;
import android.os.Build;
import android.view.LayoutInflater;
import android.view.View;

import androidx.annotation.RequiresApi;

import com.labters.documentscanner.DocumentScannerView;

import org.appcelerator.kroll.KrollDict;
import org.appcelerator.kroll.annotations.Kroll;
import org.appcelerator.titanium.TiBlob;
import org.appcelerator.titanium.proxy.TiViewProxy;
import org.appcelerator.titanium.view.TiUIView;

@Kroll.proxy(creatableInModule = TiDocumentscannerModule.class)
public class CropViewProxy extends TiViewProxy {
    private DocumentScannerView dsv;

    // Constructor
    public CropViewProxy() {
        super();
    }

    private static int exifToDegrees(int exifOrientation) {
        if (exifOrientation == ExifInterface.ORIENTATION_ROTATE_90) {
            return 90;
        } else if (exifOrientation == ExifInterface.ORIENTATION_ROTATE_180) {
            return 180;
        } else if (exifOrientation == ExifInterface.ORIENTATION_ROTATE_270) {
            return 270;
        }
        return 0;
    }

    @Override
    public TiUIView createView(Activity activity) {
        TiUIView view = new CropView(this);
        view.getLayoutParams().autoFillsHeight = true;
        view.getLayoutParams().autoFillsWidth = true;
        return view;
    }

    // Handle creation options
    @Override
    public void handleCreationDict(KrollDict options) {
        super.handleCreationDict(options);
    }

    @RequiresApi(api = Build.VERSION_CODES.N)
    @Kroll.setProperty
    public void image(TiBlob blob) {
        try {
            ExifInterface exif = new ExifInterface(blob.getInputStream());
            Bitmap bmp = blob.getImage();
            int rotation = exif.getAttributeInt(ExifInterface.TAG_ORIENTATION, ExifInterface.ORIENTATION_NORMAL);
            int rotationInDegrees = exifToDegrees(rotation);
            Matrix matrix = new Matrix();
            if (rotation != 0) {
                matrix.preRotate(rotationInDegrees);
            }

            Bitmap adjustedBitmap = Bitmap.createBitmap(bmp, 0, 0, bmp.getWidth(), bmp.getHeight(), matrix, true);
            dsv.setImage(adjustedBitmap);
        } catch (Exception e) {
            Bitmap bmp = blob.getImage();
            dsv.setImage(bmp);
        }
    }

    @Kroll.method
    public TiBlob cropImage() {
        return TiBlob.blobFromImage(dsv.getCroppedImage());
    }

    private class CropView extends TiUIView {
        public CropView(TiViewProxy proxy) {
            super(proxy);
            String packageName = proxy.getActivity().getPackageName();
            Resources resources = proxy.getActivity().getResources();
            View viewWrapper;

            int resId_viewHolder;
            int resIdPublish;

            resId_viewHolder = resources.getIdentifier("layout_main", "layout", packageName);
            resIdPublish = resources.getIdentifier("document_scanner", "id", packageName);

            LayoutInflater inflater = LayoutInflater.from(proxy.getActivity());
            viewWrapper = inflater.inflate(resId_viewHolder, null);
            dsv = (DocumentScannerView) viewWrapper.findViewById(resIdPublish);

            dsv.setOnLoadListener(loading -> {
                return null;
            });

            setNativeView(viewWrapper);
        }

        @Override
        public void processProperties(KrollDict d) {
            super.processProperties(d);
        }
    }
}
