/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Titanium SDK
 * Copyright TiDev, Inc. 04/07/2022-Present
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 */
package ti.documentscanner;

import android.app.Activity;
import android.content.Intent;

import org.appcelerator.kroll.KrollDict;
import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.KrollProxy;
import org.appcelerator.kroll.annotations.Kroll;
import org.appcelerator.titanium.TiApplication;


@Kroll.module(name = "TiDocumentscanner", id = "ti.documentscanner")
public class TiDocumentscannerModule extends KrollModule {

    public TiDocumentscannerModule() {
        super();
    }
    public static KrollProxy proxy;

    @Kroll.onAppCreate
    public static void onAppCreate(TiApplication app) {

    }

    // Methods
    @Kroll.method
    public void scan() {
        proxy = this;
        Activity activity = TiApplication.getAppCurrentActivity();
        Intent intent = new Intent(activity, TiDocumentscannerActivity.class);
        activity.startActivityForResult(intent, 1);
    }

    public static void callMe(KrollDict kd){
        proxy.fireEvent("done", kd);
    }

}

